# generated by genreads.bash
bvi <- read.table("/home/user/data/stocks/bvi.csv", sep=",", header=T)
lqd <- read.table("/home/user/data/stocks/lqd.csv", sep=",", header=T)
recent <- read.table("/home/user/data/stocks/recent.csv", sep=",", header=T)
